#!/bin/bash
Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
Info="${Green_font_prefix}[信息]${Font_color_suffix}" && Error="${Red_font_prefix}[错误]${Font_color_suffix}" && Tip="${Green_font_prefix}[注意]${Font_color_suffix}"

echo -e "${Info} clean build rubbish"

DIRS=`ls -al tmp/rootfs-build | grep "\->" | awk '{print $11}'`
for dir in $DIRS ; do \
    find $dir -name build  | xargs rm -rf ; \
    find $dir -name images | xargs rm -rf ; \
    echo -e "${Info} clean folder : " $dir ; done